DROP TABLE SCHEDURE_TBL;
DROP TABLE PLATER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;


CREATE TABLE NATION_TBL (
    N_CODE         NUMBER(3)         NOT NULL, -- NUMBER(3) : 0 ~ 999
    N_NAME         VARCHAR2(30 BYTE) NOT NULL,
    N_PARTI_PERSON NUMBER            DEFAULT(0),
    N_PARTI_EVENT  NUMBER,
    N_PREV_RANK    NUMBER,
    N_CURR_RANK    NUMBER
);

CREATE TABLE EVENT_TBL (
    E_CODE       NUMBER            NOT NULL,
    E_NAME       VARCHAR2(30 BYTE) NOT NULL,
    E_FIRST_YEAR NUMBER(4),
    E_INFO       VARCHAR2(100 BYTE)
);

CREATE TABLE PLAYER_TBL (
    P_CODE NUMBER(3)         NOT NULL,
    P_NAME VARCHAR2(30 BYTE) NOT NULL,
    N_CODE NUMBER(3)         NOT NULL,
    E_CODE NUMBER            NOT NULL,
    P_RANK NUMBER,
    P_AGE  NUMBER(3)
);

CREATE TABLE SCHEDULE_TBL (
    S_NO         NUMBER(3)          NOT NULL,
    N_CODE       NUMBER(3),
    E_CODE       NUMBER,
    S_START_DATE DATE,
    S_END_DATE   DATE,
    S_INFO       VARCHAR2(100 BYTE)
);

-- 기본키 추가하기
ALTER TABLE NATION_TBL ADD CONSTRAINT PK_NATION PRIMARY KEY(N_CODE);
ALTER TABLE EVENT_TBL ADD CONSTRAINT PK_EVENT PRIMARY KEY(E_CODE);
ALTER TABLE PLAYER_TBL ADD CONSTRAINT PK_PLAYER PRIMARY KEY(P_CODE);
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY(S_NO);

-- 외래키 추가하기
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_NATION_PLAYER FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE CASCADE; -- PLAYER_TBL의 N_CODE가 NOT NULL이므로, ON DELETE SET NULL이 불가능
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_EVENT_PLAYER FOREIGN KEY(E_CODE) REFERENCES EVENT_TBL(E_CODE) ON DELETE CASCADE; -- PLAYER_TBL의 E_CODE가 NOT NULL이므로, ON DELETE SET NULL이 불가능

ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_NATION_SCHEDURE FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE SET NULL;  -- ON DELETE CASCADE도 가능
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_EVENT_SCHEDURE FOREIGN KEY(N_CODE) REFERENCES EVENT_TBL(N_CODE) ON DELETE SET NULL; -- ON DELETE CASCADE도 가능

